version: '3'

volumes:
  mysql_data:
      driver: local

services:
  db:
      image: mysql:8
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      #container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
        TZ: Asia/Tokyo # change your timezone
      ports:
        - 3306:3306
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      volumes:
        - ./keycloak/account.ftl:/opt/jboss/keycloak/themes/base/account/account.ftl
        - ./keycloak/register.ftl:/opt/jboss/keycloak/themes/base/login/register.ftl
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_FRONTEND_URL: http://${HOST:-localhost}:8180/auth
      ports:
        - 8180:8080
      healthcheck:
        test: '/opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password admin;/opt/jboss/keycloak/bin/kcadm.sh update realms/master -s registrationAllowed=true;/opt/jboss/keycloak/bin/kcadm.sh update "realms/master" -s accountTheme=keycloak || exit 1'
      depends_on:
        - db
  easybuggy:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8080:8080
        - 9009:9009
      depends_on:
        keycloak:
          condition: service_healthy
      environment:
        db_url: jdbc:mysql://db:3306/keycloak?useSSL=false
        db_class_name: com.mysql.jdbc.Driver
        db_platform: mysql
        db_username: keycloak
        db_password: password
        oidc_config_endpoint: http://keycloak:8080/auth/realms/master/.well-known/openid-configuration
        oidc_dynamic_client_registration_enabled: 'true'
        attacker_app_url: http://${HOST:-localhost}:9999/attacker_app
        manage_account_page_url: http://${HOST:-localhost}:8180/auth/realms/master/account/
  attacker_app:
    build: ./attacker_app
    ports:
      - 9999:8080
  mail:
    image: python:3
    ports:
      - 1025:1025
    command: python -m smtpd -d -n -c DebuggingServer 0.0.0.0:1025